### ISSUE TITLE
Error on DB

### ISSUE THREAD

**Issue by lucasbordini** [rodion-arr/nestjs-starter-kit#30]
Hi,

I`m really new on NestJS (trying my first project)
and really like your starter, has a lot of usefull things

but following your instructions, when I try to migrate my db I receveing this error:

Error during migration run:
Error: getaddrinfo ENOTFOUND db
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'db'
}

can you help-me with this ? probably is something stupid that I dont know

**Comment by rodion-arr** [comment]
Hi, thank you for interest to the project.

> hostname: 'db'
It looks like I have an incorrect value in `.env.example`, it should be
```env
DB_HOST=localhost
```

Please update db host to `localhost` in your `.env` and `ormconfig.json` files, it should fix the issue

**Comment by rodion-arr** [comment]
I believe my comment above should fix the issue, so I'm closing the ticket. Feel free to reopen in case it wasn't help
